### ISSUE TITLE
CLI issue on windows

### ISSUE THREAD

**Issue by bin0x00** [MarkMichon1/BitGlitter#14]
I have an error when trying CLI 
```No module named bitglitter.__main__; 'bitglitter' is a package and cannot be directly executed```

**Comment by Drunpy** [comment]
Can you provide the exact command and args ?

**Comment by hidely** [comment]
Note: python3 = python, changed in the path
commend: python -m bitglitter write "path/to/my/file

**Comment by ChildishGiant** [comment]
```
PS D:\programs\youtube-dl> py -m bitglitter read '.\default config test-HrY4deFrOoA.mp4'
C:\Users\Allie\AppData\Local\Programs\Python\Python37-32\python.exe: No module named bitglitter.__main__; 'bitglitter' is a package and cannot be directly executed
PS D:\programs\youtube-dl>

```

**Comment by Drunpy** [comment]
We have already identified this issue and it will be fixed in the following
days.

Em sáb, 20 de jul de 2019 14:02, Allie <notifications@github.com> escreveu:
