### ISSUE TITLE
I keep getting this error. Help!

### ISSUE THREAD

**Issue by ThatOneCalculator** [MarkMichon1/BitGlitter#7]
```


>>> write("Untitled.png")
21:28:43.888 INFO Verifying write parameters...
21:28:43.888 INFO 84.72% of the frame for initial header is allocated for frame payload (higher is better)
21:28:43.888 INFO 20992 B, or 97.17% of subsequent frames is allocated for frame payload (higher is better)
21:28:43.888 INFO As a video, it will effectively be transporting 78720 B/sec of data.
21:28:43.888 INFO Minimum geometry requirements met.
21:28:43.888 INFO Write parameters validated.
21:28:43.888 INFO Preprocess initializing...
21:28:43.889 INFO Preparing files for packaging...
21:28:43.893 INFO Packaging files...
21:28:44.005 INFO Packaging complete.
21:28:44.005 INFO Compressing package...
21:28:44.015 INFO Compression complete.
21:28:44.016 INFO SHA-256: 4f0c214d46c48b861a3570cd821a0c5129c616481d974078cd0055925fb87362
21:28:44.016 INFO Skipping encryption.
21:28:44.016 INFO Package size: 61764B
21:28:44.016 INFO Preprocess complete.
21:28:44.028 INFO 24 frame(s) required for this operation.
21:28:44.029 INFO Rendering frame 1 of 24 ...
21:28:44.676 INFO Rendering frame 2 of 24 ...
21:28:45.237 INFO Rendering frame 3 of 24 ...
21:28:45.741 INFO Rendering frame 4 of 24 ...
21:28:46.052 INFO Rendering frame 5 of 24 ...
21:28:46.376 INFO Rendering frame 6 of 24 ...
21:28:46.683 INFO Rendering frame 7 of 24 ...
21:28:46.994 INFO Rendering frame 8 of 24 ...
21:28:47.295 INFO Rendering frame 9 of 24 ...
21:28:47.594 INFO Rendering frame 10 of 24 ...
21:28:47.899 INFO Rendering frame 11 of 24 ...
21:28:48.222 INFO Rendering frame 12 of 24 ...
21:28:48.528 INFO Rendering frame 13 of 24 ...
21:28:48.896 INFO Rendering frame 14 of 24 ...
21:28:49.226 INFO Rendering frame 15 of 24 ...
21:28:49.554 INFO Rendering frame 16 of 24 ...
21:28:49.885 INFO Rendering frame 17 of 24 ...
21:28:50.199 INFO Rendering frame 18 of 24 ...
21:28:50.510 INFO Rendering frame 19 of 24 ...
21:28:50.835 INFO Rendering frame 20 of 24 ...
21:28:51.140 INFO Rendering frame 21 of 24 ...
21:28:51.453 INFO Rendering frame 22 of 24 ...
21:28:51.753 INFO Rendering frame 23 of 24 ...
21:28:52.098 INFO Rendering frame 24 of 24 ...
21:28:52.407 INFO Rendering video...
21:28:52.408 INFO 2019-05-30 21-28-44.mp4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37\lib\site-packages\bitglitter\write\write.py", line 70, in write
    framesPerSecond, activePath, preProcess.passThrough)
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37\lib\site-packages\bitglitter\write\renderhandler.py", line 76, in __init__
    self.streamName, self.streamDescription, self.postEncryptionHash)
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37\lib\site-packages\bitglitter\protocols\protocol_one\write\protocol_one_renderlogic.py", line 126, in beginSessionProcess
    self.framesPerSecond)
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37\lib\site-packages\bitglitter\write\rendervideo.py", line 15, in renderVideo
    .output(f'{videoOutputPath}{time.strftime("%Y-%m-%d %H-%M-%S", time.localtime(dateCreated))}.mp4')
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37\lib\site-packages\ffmpeg\_run.py", line 300, in run
    overwrite_output=overwrite_output,
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37\lib\site-packages\ffmpeg\_run.py", line 272, in run_async
    args, stdin=stdin_stream, stdout=stdout_stream, stderr=stderr_stream)
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>>

**Comment by MarkMichon1** [comment]
Hi there, this is probably the most common issue I've been hearing today.  BitGlitter requires ffmpeg.exe to be in the same directory as the code that is running at this time.  ffmpeg is what takes the rendered png frames, and converts them into an mp4.  I'm still figuring out the best way to have this automatically downloaded along with the package, so this will need to be manually downloaded.

Please check out the [installation notes](https://github.com/MarkMichon1/BitGlitter#installation) for more information.  Once that's downloaded you should be good to go!

**Comment by ThatOneCalculator** [comment]
oh ok. I already have ffmpeg installed, but ill put the exe in the folder. thanks!

**Comment by ThatOneCalculator** [comment]
it's compiling now :) I'll let you know if i get a good result :)

**Comment by reillykw** [comment]
Is this linux compatible?  I've got ffmpeg, having issues encoding data.

**Comment by ThatOneCalculator** [comment]
Idk tbh
I'll try it out on my Ubuntu machine tommorow

**Comment by ThatOneCalculator** [comment]
Hey, I've been trying it out w/ multiple files, will it always be 4695 frames??

**Comment by ThatOneCalculator** [comment]
or somewhere around there?

**Comment by MarkMichon1** [comment]
> 
> 
> Is this linux compatible? I've got ffmpeg, having issues encoding data.

I have opened a new issue for Linux problems:

https://github.com/MarkMichon1/BitGlitter/issues/8

**Comment by MarkMichon1** [comment]
> 
> 
> Hey, I've been trying it out w/ multiple files, will it always be 4695 frames??

The amount of frames depends on the size of the payload, assuming all other configs stay constant.

**Comment by MarkMichon1** [comment]
> ```
> >>> write("Untitled.png")

This could've been your problem.  The initial argument requires a tuple, not a string.  It was developed this way early on so end users can add arbitrary amounts of files and/or folders into it, and the program would simply iterate over the results from there.  When a tuple isn't used, the program will sometimes immediately crash, and other times run all the way until video render and then throw an exception.  Here's an example of how it should look: `write(('C:\\Users\\Mark\\Desktop\\somefile.pdf',))`

You're not the first person to mention this today either.  I think I'll add the functionality to accept a string as the initial `fileList` argument if there is only one file or folder path.

**Comment by ThatOneCalculator** [comment]
ok
also, i've been writing a 1kb file now for 30 minutes. I don't think thats normal...

**Comment by ThatOneCalculator** [comment]
oh i restarted it w/ the tuple. now it's going at expected speeds :)

**Comment by ThatOneCalculator** [comment]
hold on, it's just a half-second video of a black screen o_0

**Comment by ThatOneCalculator** [comment]
any idea why that could be?

**Comment by MarkMichon1** [comment]
> 
> 
> any idea why that could be?

I do.  A one kilobyte file would be quite tiny, even for BitGlitter standards.  If you're using the default configs, I think that could be transported in the first frame, perhaps two.  So from what you've told me, you have a one or two frame long video.

**Comment by ThatOneCalculator** [comment]
it read. If it works, it works lol. ill try w/ a bigger file later

**Comment by ThatOneCalculator** [comment]
update: a new error:


```


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37\lib\site-packages\bitglitter\write\write.py", line 61, in write
    scryptOverrideN, scryptOverrideR, scryptOverrideP)
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37\lib\site-packages\bitglitter\protocols\protocol_one\write\protocol_one_preprocess.py", line 21, in __init__
    packager = Packager(self.activeFolder, fileList, maskFiles)
  File "C:\Users\algeb\AppData\Local\Programs\Python\Python37\lib\site-packages\bitglitter\protocols\protocol_one\write\protocol_one_preprocessobjects.py", line 34, in __init__
    raise ValueError("No valid files or folders were found from your fileList tuple in write()")
ValueError: No valid files or folders were found from your fileList tuple in write()
>>>

**Comment by MarkMichon1** [comment]
> 
> 
> update: a new error

Could you copy and paste the code you used to call `write()`?  Thanks.

**Comment by ThatOneCalculator** [comment]
i did. my bad, i made a typo in the filename

**Comment by MarkMichon1** [comment]
Good deal.  Let me know if you come across any other issues.

**Comment by ThatOneCalculator** [comment]
ok. im going to try it with a 40 second video

**Comment by ThatOneCalculator** [comment]
After it finished writing and started ffmpeg proccessing, it crashed :(

**Comment by ThatOneCalculator** [comment]
![image](https://user-images.githubusercontent.com/44733677/58683968-54bcc300-832b-11e9-98a8-117ac4eab55f.png)

**Comment by ThatOneCalculator** [comment]
I tried it again and the same thing happened, this time on a 500kb png

**Comment by ThatOneCalculator** [comment]
:(((

**Comment by MarkMichon1** [comment]
What it very well could be is the window hanging as it renders the video.  Once the logging messages for ffmpeg begin, there are no other status messages until that process is complete.  Depending on how many frames there are in the video and the specs of your machine, that may take a little bit of time.

But to reiterate, you're not receiving any Python exceptions, the window/instance itself is crashing.  Do I understand that correctly?

**Comment by ThatOneCalculator** [comment]
Yes. But now, an even weirder thing happened. A video actually appeared in the folder with an apparent ***negative time*** and now I can apparently read it...

**Comment by ThatOneCalculator** [comment]
I don't understand XD

**Comment by MarkMichon1** [comment]
Yeah I don't either lol.... when you say negative time, what do you mean?

**Comment by ThatOneCalculator** [comment]
VLC said "0:00 -> -0.25"

Also for whatever reason it read the file perfectly fine

**Comment by ThatOneCalculator** [comment]
[multi_maybe.zip](https://github.com/MarkMichon1/BitGlitter/files/3239867/multi_maybe.zip)

**Comment by MarkMichon1** [comment]
Hmm, I don't know why VLC would be displaying that.  As long the video file isn't corrupted and it still reads....

**Comment by ThatOneCalculator** [comment]
Image it made (exactly the same):

![multi](https://user-images.githubusercontent.com/44733677/58684403-090b1900-832d-11e9-9b5c-b582d3fe6fd1.png)

**Comment by ThatOneCalculator** [comment]
It worked

**Comment by ThatOneCalculator** [comment]
Idk how

**Comment by MarkMichon1** [comment]
I'm not seeing any negative values, perhaps VLC is displaying remaining time left for it?

**Comment by MarkMichon1** [comment]
And I'm happy to hear it is.

**Comment by ThatOneCalculator** [comment]
I'm going to try it with a bigger file to see if I can actually see the pixel art

**Comment by ThatOneCalculator** [comment]
I'll keep you posted

**Comment by MarkMichon1** [comment]
I think we're good to go here.  If you have a specific issue, please submit another issue ticket and I'll check it out.  Otherwise, join us on the Discord channel, the link is on the top of the readme.  That's a more appropriate place to have conversations.
